name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v1
        with:
          runtime: node@lts
          cache: true

      - name: Run lint
        run: 'pnpm lint'

      - name: Run build
        run: 'pnpm build'
